networks:
  d2ray_br:
    external: false

services:
  d2ray:
    image: d2ray
    container_name: d2ray
    ports:
      - 443:8443
    environment:
      - HOST=localhost
      - PORT=443
      - TARGET_HOST=freebsd.org
      - TARGET_PORT=443
      - USERS=alice,bob,eve
      - BLOCK_CN=true
      - BLOCK_ADS=true
      - BLOCK_LOCAL=true
      - PRIVATE_KEY=KE5MCI5e395fub55O1lsNPzvWw9nNAyCaecRSp3BvHg # Do NOT use this random key
      - LOG_LEVEL=warning
    restart: unless-stopped
    networks:
      - d2ray_br
    volumes:
      - ./config:/etc/d2ray
